import {
  pgTable,
  uuid,
  text,
  timestamp,
  boolean,
  integer,
  jsonb,
  index,
  uniqueIndex,
  customType,
} from 'drizzle-orm/pg-core';

/** Postgres tsvector. Generated by the database — never written by the app. */
const tsvector = customType<{ data: string; notNull: false; default: false }>({
  dataType: () => 'tsvector',
});
import { institutions, departments } from './tenancy';
import { users } from './people';
import { subjects, courseOfferings, sections } from './academics';
import { resourceKindEnum, resourceStatusEnum } from './enums';

/**
 * ACADEMIC RESOURCE HUB
 * ---------------------------------------------------------------------------
 * Institutional teaching material with structured tagging and keyword search.
 *
 * SEARCH: this MVP uses PostgreSQL full-text search over title/description/
 * extracted text (see the `searchVector` column and the GIN index created in
 * the migration). A pluggable `ResourceSearchProvider` interface allows a
 * vector/embedding backend to be added later without touching call sites —
 * see src/services/resources/search.ts. We do NOT claim semantic search here.
 */

export const resources = pgTable(
  'resources',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    institutionId: uuid('institution_id')
      .notNull()
      .references(() => institutions.id, { onDelete: 'cascade' }),
    title: text('title').notNull(),
    description: text('description'),
    kind: resourceKindEnum('kind').notNull().default('DOCUMENT'),
    status: resourceStatusEnum('status').notNull().default('DRAFT'),

    /** Either a stored file or an external link. */
    fileUrl: text('file_url'),
    fileName: text('file_name'),
    fileSizeBytes: integer('file_size_bytes'),
    mimeType: text('mime_type'),
    externalUrl: text('external_url'),
    /** Text extracted from the file, used for search and for grounding AI answers. */
    extractedText: text('extracted_text'),

    ownerId: uuid('owner_id').references(() => users.id, { onDelete: 'set null' }),
    departmentId: uuid('department_id').references(() => departments.id, { onDelete: 'set null' }),
    subjectId: uuid('subject_id').references(() => subjects.id, { onDelete: 'set null' }),
    offeringId: uuid('offering_id').references(() => courseOfferings.id, { onDelete: 'set null' }),

    topic: text('topic'),
    semester: integer('semester'),
    /** BEGINNER | INTERMEDIATE | ADVANCED */
    difficulty: text('difficulty'),
    academicYear: text('academic_year'),

    /** True until a human approves AI-produced material. Surfaced in the UI. */
    isAiGenerated: boolean('is_ai_generated').notNull().default(false),
    aiGenerationId: uuid('ai_generation_id'),
    approvedById: uuid('approved_by_id').references(() => users.id, { onDelete: 'set null' }),
    approvedAt: timestamp('approved_at', { withTimezone: true }),

    /** Visibility: PRIVATE (owner) | DEPARTMENT | INSTITUTION | SECTION */
    visibility: text('visibility').notNull().default('DEPARTMENT'),
    viewCount: integer('view_count').notNull().default(0),
    downloadCount: integer('download_count').notNull().default(0),

    /**
     * Generated column maintained by PostgreSQL (see 0001_hard_constraints.sql).
     * Declared here so queries can reference it; never included in inserts.
     */
    searchVector: tsvector('search_vector'),

    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
  },
  (t) => [
    index('resources_institution_idx').on(t.institutionId, t.status),
    index('resources_subject_idx').on(t.subjectId),
    index('resources_owner_idx').on(t.ownerId),
  ],
);

export const resourceTags = pgTable(
  'resource_tags',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    institutionId: uuid('institution_id')
      .notNull()
      .references(() => institutions.id, { onDelete: 'cascade' }),
    resourceId: uuid('resource_id')
      .notNull()
      .references(() => resources.id, { onDelete: 'cascade' }),
    tag: text('tag').notNull(),
    /** MANUAL | AI_SUGGESTED | DERIVED */
    source: text('source').notNull().default('MANUAL'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex('resource_tags_uq').on(t.resourceId, t.tag),
    index('resource_tags_tag_idx').on(t.institutionId, t.tag),
  ],
);

/** Which sections a resource has been shared with (when visibility = SECTION). */
export const resourceShares = pgTable(
  'resource_shares',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    institutionId: uuid('institution_id')
      .notNull()
      .references(() => institutions.id, { onDelete: 'cascade' }),
    resourceId: uuid('resource_id')
      .notNull()
      .references(() => resources.id, { onDelete: 'cascade' }),
    sectionId: uuid('section_id').references(() => sections.id, { onDelete: 'cascade' }),
    userId: uuid('user_id').references(() => users.id, { onDelete: 'cascade' }),
    sharedAt: timestamp('shared_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index('resource_shares_resource_idx').on(t.resourceId)],
);

/**
 * Lesson plans produced by the Teacher Copilot. Stored structurally (not as a
 * blob of markdown) so sections can be edited, regenerated and reused.
 */
export const lessonPlans = pgTable(
  'lesson_plans',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    institutionId: uuid('institution_id')
      .notNull()
      .references(() => institutions.id, { onDelete: 'cascade' }),
    offeringId: uuid('offering_id').references(() => courseOfferings.id, { onDelete: 'cascade' }),
    subjectId: uuid('subject_id').references(() => subjects.id, { onDelete: 'set null' }),
    authorId: uuid('author_id').references(() => users.id, { onDelete: 'set null' }),
    title: text('title').notNull(),
    topic: text('topic').notNull(),
    durationMinutes: integer('duration_minutes').notNull().default(60),
    /** Structured plan: objectives, structure[], activities[], quiz[], homework, misconceptions[] */
    content: jsonb('content').$type<Record<string, unknown>>().notNull(),
    status: resourceStatusEnum('status').notNull().default('AI_GENERATED_PENDING_REVIEW'),
    isAiGenerated: boolean('is_ai_generated').notNull().default(true),
    aiGenerationId: uuid('ai_generation_id'),
    /** Minutes the faculty would plausibly have spent doing this manually. */
    estimatedManualMinutes: integer('estimated_manual_minutes').notNull().default(30),
    actualMinutesSpent: integer('actual_minutes_spent'),
    scheduledFor: timestamp('scheduled_for', { withTimezone: true }),
    publishedAt: timestamp('published_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
  },
  (t) => [
    index('lesson_plans_institution_idx').on(t.institutionId),
    index('lesson_plans_author_idx').on(t.authorId),
    index('lesson_plans_offering_idx').on(t.offeringId),
  ],
);
