import 'server-only';
import { createHash, randomUUID } from 'node:crypto';
import { and, eq, isNull, or, sql } from 'drizzle-orm';
import { db } from '@/lib/db';
import * as t from '@/lib/db/schema';
import { AppError, ForbiddenError, NotFoundError } from '@/lib/api';
import type { AuthContext } from '@/lib/auth/context';
import { recordAudit } from '@/services/audit';
import { enforceRateLimit, keyFor, RATE_LIMITS } from '@/services/rate-limit';
import { getScanner } from './scanner';
import { getStorageProvider, maxUploadBytes, type StorageProvider } from './providers';
import { validateUpload } from './validate';
import { resourceVisibilityFor } from '@/services/resources';

/**
 * FILE STORAGE SERVICE
 * ---------------------------------------------------------------------------
 * validate (type by content, size) → scan → store → record metadata → audit.
 * Reads are authorised per purpose, then streamed (local) or redirected to a
 * five-minute pre-signed URL (S3-compatible).
 */

export const STORAGE_UNAVAILABLE_MESSAGE =
  'File storage is not configured for this deployment, so files can’t be uploaded. Add a link to where the file already lives instead, or ask your administrator to configure storage.';

export function storageAvailable(): boolean {
  return getStorageProvider() !== null;
}

export interface StoredFileSummary {
  id: string;
  url: string;
  name: string;
  mimeType: string;
  sizeBytes: number;
  scanStatus: string;
}

export function fileUrl(id: string): string {
  return `/api/files/${id}`;
}

/** Who may upload for each purpose (any one of the listed permissions). AVATAR: anyone. */
const PURPOSE_PERMISSIONS: Record<string, string[]> = {
  RESOURCE: ['resource:upload'],
  ANNOUNCEMENT: ['announcement:create_informational', 'announcement:create_official'],
  SUBMISSION: ['assignment:submit'],
  EVENT_COVER: ['event:create'],
  VERIFICATION_ID: ['file:upload'],
};

/** College IDs are small scans or photos; keep the cap tight whatever the global limit. */
const VERIFICATION_ID_MAX_BYTES = 8 * 1024 * 1024;

export async function uploadFile(
  ctx: AuthContext,
  input: { name: string; bytes: Uint8Array; purpose: string; meta?: { ipAddress: string | null; userAgent: string | null } },
  provider: StorageProvider | null = getStorageProvider(),
): Promise<StoredFileSummary> {
  if (!provider) throw new AppError(STORAGE_UNAVAILABLE_MESSAGE, 501, 'STORAGE_NOT_CONFIGURED');
  if (input.purpose === 'DATA_EXPORT') throw new ForbiddenError('Data exports are generated by CampusOS, not uploaded.');
  // A purpose decides who may later read the file, so it must match what the uploader may publish.
  const needs = PURPOSE_PERMISSIONS[input.purpose];
  if (needs && !needs.some((p) => ctx.permissions.has(p as never))) throw new ForbiddenError('You can’t upload files for that.');
  await enforceRateLimit(keyFor('upload', ctx.userId), RATE_LIMITS.uploadPerUser, 'Upload limit reached for this hour.');

  const maxBytes = input.purpose === 'VERIFICATION_ID' ? Math.min(maxUploadBytes(), VERIFICATION_ID_MAX_BYTES) : maxUploadBytes();
  const check = validateUpload({ name: input.name, bytes: input.bytes, purpose: input.purpose, maxBytes });
  if (!check.ok) throw new AppError(check.message, check.code === 'TOO_LARGE' ? 413 : 422, check.code);

  const scan = await getScanner().scan(input.bytes);
  if (scan.status === 'INFECTED') {
    await recordAudit(ctx, {
      action: 'FILE_UPLOADED',
      entityType: 'file',
      reason: `Rejected by ${scan.engine} scanner: ${scan.detail ?? 'threat detected'}`,
      after: { name: check.name, purpose: input.purpose, rejected: true },
    });
    throw new AppError('This file was blocked by the security scanner.', 422, 'FILE_REJECTED', undefined,
      'If you believe this is a mistake, contact IT support.');
  }

  return storeBytes(ctx, {
    provider,
    purpose: input.purpose,
    name: check.name,
    mime: check.mime,
    extension: check.extension,
    bytes: input.bytes,
    scanStatus: scan.status,
    scanDetail: scan.detail ?? `engine=${scan.engine}`,
    meta: input.meta,
  });
}

/** Stores server-generated bytes (e.g. a data export). Skips upload validation. */
export async function storeBytes(
  ctx: Pick<AuthContext, 'userId' | 'institutionId' | 'role'>,
  p: {
    provider?: StorageProvider | null;
    purpose: string;
    name: string;
    mime: string;
    extension: string;
    bytes: Uint8Array;
    scanStatus: 'CLEAN' | 'NOT_SCANNED';
    scanDetail?: string;
    meta?: { ipAddress: string | null; userAgent: string | null };
  },
): Promise<StoredFileSummary> {
  const provider = p.provider === undefined ? getStorageProvider() : p.provider;
  if (!provider) throw new AppError(STORAGE_UNAVAILABLE_MESSAGE, 501, 'STORAGE_NOT_CONFIGURED');

  const now = new Date();
  const key = [
    ctx.institutionId,
    p.purpose.toLowerCase(),
    String(now.getUTCFullYear()),
    String(now.getUTCMonth() + 1).padStart(2, '0'),
    `${randomUUID()}.${p.extension}`,
  ].join('/');
  const sha256 = createHash('sha256').update(p.bytes).digest('hex');

  await provider.put(key, p.bytes, p.mime);
  let row;
  try {
    [row] = await db
      .insert(t.storedFiles)
      .values({
        institutionId: ctx.institutionId,
        ownerId: ctx.userId,
        purpose: p.purpose,
        provider: provider.name,
        storageKey: key,
        originalName: p.name,
        mimeType: p.mime,
        sizeBytes: p.bytes.length,
        sha256,
        scanStatus: p.scanStatus,
        scanDetail: p.scanDetail ?? null,
      })
      .returning();
  } catch (error) {
    // Don't leave an orphaned object if the metadata write fails.
    await provider.delete(key).catch(() => undefined);
    throw error;
  }

  await recordAudit(ctx, {
    action: 'FILE_UPLOADED',
    entityType: 'file',
    entityId: row!.id,
    after: { name: p.name, purpose: p.purpose, sizeBytes: p.bytes.length, scan: p.scanStatus },
    ...(p.meta ?? {}),
  });

  return {
    id: row!.id,
    url: fileUrl(row!.id),
    name: row!.originalName,
    mimeType: row!.mimeType,
    sizeBytes: row!.sizeBytes,
    scanStatus: row!.scanStatus,
  };
}

/**
 * Authorises a read. Same tenant is necessary but not sufficient:
 *   DATA_EXPORT        owner only
 *   RESOURCE           per the resource's visibility (PRIVATE → owner / managers)
 *   ANNOUNCEMENT, EVENT_COVER, AVATAR   any member of the institution
 *   SUBMISSION                          owner, or staff who evaluate assignments
 *   VERIFICATION_ID (and anything else) owner only — college reviewers read an
 *                                       ID through its membership request
 *                                       (services/membership.ts), never here
 */
export async function authorizeFileRead(ctx: AuthContext, fileId: string) {
  const [file] = await db
    .select()
    .from(t.storedFiles)
    .where(and(eq(t.storedFiles.id, fileId), eq(t.storedFiles.institutionId, ctx.institutionId), isNull(t.storedFiles.deletedAt)))
    .limit(1);
  // Same answer for "does not exist" and "belongs to another college".
  if (!file) throw new NotFoundError('File');
  const isOwner = file.ownerId === ctx.userId;

  switch (file.purpose) {
    case 'DATA_EXPORT':
      if (!isOwner) throw new NotFoundError('File');
      break;
    case 'RESOURCE': {
      if (isOwner) break;
      // The same visibility rule as every resource list: published, and visible to this person.
      const [resource] = await db
        .select({ id: t.resources.id })
        .from(t.resources)
        .where(and(eq(t.resources.fileUrl, fileUrl(file.id)), resourceVisibilityFor(ctx)))
        .limit(1);
      if (!resource) throw new NotFoundError('File');
      break;
    }
    case 'ANNOUNCEMENT':
    case 'EVENT_COVER':
    case 'AVATAR':
      break;
    case 'SUBMISSION': {
      if (isOwner) break;
      // Only staff who may see every assignment, or the faculty who teach the class.
      if (ctx.permissions.has('assignment:view_all')) break;
      if (!ctx.facultyProfileId || !ctx.permissions.has('assignment:evaluate')) throw new NotFoundError('File');
      const url = fileUrl(file.id);
      const [teaching] = await db
        .select({ id: t.submissions.id })
        .from(t.submissions)
        .innerJoin(t.assignments, eq(t.assignments.id, t.submissions.assignmentId))
        .innerJoin(t.courseOfferings, eq(t.courseOfferings.id, t.assignments.offeringId))
        .where(
          and(
            eq(t.submissions.institutionId, ctx.institutionId),
            sql`${t.submissions.attachments}::jsonb @> ${JSON.stringify([{ url }])}::jsonb`,
            or(eq(t.courseOfferings.facultyId, ctx.facultyProfileId), eq(t.courseOfferings.secondaryFacultyId, ctx.facultyProfileId)),
          ),
        )
        .limit(1);
      if (!teaching) throw new NotFoundError('File');
      break;
    }
    default:
      if (!isOwner) throw new NotFoundError('File');
  }
  if (file.scanStatus === 'INFECTED') throw new NotFoundError('File');
  return file;
}

export type FileReadResult =
  | { kind: 'redirect'; url: string }
  | { kind: 'bytes'; bytes: Buffer; mimeType: string; name: string };

export async function readFileFor(ctx: AuthContext, fileId: string): Promise<FileReadResult> {
  const file = await authorizeFileRead(ctx, fileId);
  const provider = getStorageProvider();
  if (!provider || provider.name !== file.provider) {
    throw new AppError('This file is stored with a provider that is not configured on this server.', 503, 'STORAGE_UNAVAILABLE');
  }
  if (file.purpose === 'DATA_EXPORT') {
    await recordAudit(ctx, { action: 'DATA_EXPORT_DOWNLOADED', entityType: 'file', entityId: file.id });
  }
  if (provider.signedUrl) {
    return { kind: 'redirect', url: await provider.signedUrl(file.storageKey, { expiresSec: 300, downloadName: file.originalName }) };
  }
  return { kind: 'bytes', bytes: await provider.read!(file.storageKey), mimeType: file.mimeType, name: file.originalName };
}
